version: '3'
services:
  # jenkins:
    # container_name: jenkins
    # image: devops-jenkins-ansible
    # build:
      # context: jenkins-ansible
    # ports:
      # - "8080:8080"
    # volumes:
      # - $PWD/jenkins_home:/var/jenkins_home
  puppet:
    container_name: puppet
    image: devops-puppet-master
    hostname: puppet
    build:
      context: puppet-master
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  remote_host:
    container_name: remote-host
    image: devops-remote-host
    hostname: remote-host
    build:
      context: remote-host
    ports:
      - "8888:80"
      - "8443:443"
  # git:
    # container_name: git-server
    # hostname: gitlab.example.com
    # ports:
      # - "443:443"
      # - "80:80"
    # volumes:
      # - $PWD/gitlab/config:/etc/gitlab
      # - $PWD/gitlab/logs:/var/log/gitlab
      # - $PWD/gitlab/data:/var/opt/gitlab"
    # image: gitlab/gitlab-ce
