version: '3'
services:
  # jenkins:
    # container_name: jenkins
    # image: devops-jenkins-ansible
    # build:
      # context: jenkins-ansible
    # ports:
      # - "8080:8080"
    # volumes:
      # - $PWD/jenkins_home:/var/jenkins_home
  puppet:
    container_name: puppet
    image: devops-puppet-master
    hostname: puppet
    build:
      context: puppet-master
    volumes:
      - ./volumes/puppet-master/modules:/etc/puppetlabs/code/environments/production/modules:rw
      - ./volumes/puppet-master/hieradata:/etc/puppetlabs/code/environments/production/nodes:ro
      - ./volumes/puppet-master/manifests:/etc/puppetlabs/code/environments/production/manifests:ro
  remote_host:
    container_name: remote-host
    image: devops-remote-host
    hostname: remote-host
    build:
      context: remote-host
    ports:
      - "8888:80"
      - "8443:443"
    depends_on:
      - puppet
  remote_host2:
    container_name: remote-host-2
    image: devops-remote-host
    hostname: remote-host-2
    depends_on:
      - puppet
    # command: puppet agent -t && "while true; do sleep 30; done;"
  # git:
    # container_name: git-server
    # hostname: gitlab.example.com
    # ports:
      # - "443:443"
      # - "80:80"
    # volumes:
      # - ./volumes/gitlab/config:/etc/gitlab
      # - ./volumes/gitlab/logs:/var/log/gitlab
      # - ./volumes/gitlab/data:/var/opt/gitlab"
    # image: gitlab/gitlab-ce
