version: '3'
services:
  # jenkins:
    # container_name: jenkins
    # image: devops-jenkins
    # build:
      # context: jenkins
    # ports:
      # - "8080:8080"
    # volumes:
      # - ./volumes/jenkins/jenkins_home:/var/jenkins_home
  puppet:
    container_name: puppet
    image: devops-puppet-master
    hostname: puppet
    build:
      context: docker/puppet-master
    volumes:
      - ./volumes/puppet-master/modules:/etc/puppetlabs/code/environments/production/modules:rw
      - ./volumes/puppet-master/hieradata:/etc/puppetlabs/code/environments/production/nodes:ro
      - ./volumes/puppet-master/manifests:/etc/puppetlabs/code/environments/production/manifests:ro
  server_1:
    container_name: server-1
    image: devops-server
    hostname: server-1
    build:
      context: docker/server
    ports:
      - "8888:80"
      - "8443:443"
    depends_on:
      - puppet
  server_2:
    container_name: server-2
    image: devops-server
    hostname: server-2
    depends_on:
      - puppet
  # git:
    # container_name: git-server
    # hostname: gitlab.example.com
    # ports:
      # - "443:443"
      # - "80:80"
    # volumes:
      # - ./volumes/gitlab/config:/etc/gitlab
      # - ./volumes/gitlab/logs:/var/log/gitlab
      # - ./volumes/gitlab/data:/var/opt/gitlab"
    # image: gitlab/gitlab-ce
